(ns cljs-rx.observable
  (:refer-clojure :exclude [take merge])
  (:use-macros [cljs-rx.macros :only [defwrap]]))

(defwrap select .select 1)
(defwrap select-many .selectMany 1)
(defwrap throttle .throttle 1)
(defwrap distinct-until-changed .distinctUntilChanged)
(defwrap where .where 1)
(defwrap switch-latest .switchLatest)
(defwrap subscribe .subscribe 1 2)
(defwrap delay .delay 1)
(defwrap take-until .takeUntil 1)
(defwrap buffer-with-count .bufferWithCount 2)
(defwrap take .take 1)
(defwrap merge .merge 1)